'use server';
/**
 * @fileOverview An AI agent that suggests a full list of line items (parts and labor) for a quote.
 * It uses the project description, user prompt, uploaded documents (RFQs, plans), and previous quotes as context.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import type { SuggestQuoteLineItemsInput, SuggestQuoteLineItemsOutput } from '@/lib/types';

export async function suggestQuoteLineItems(
  input: SuggestQuoteLineItemsInput
): Promise<SuggestQuoteLineItemsOutput> {
  return suggestQuoteLineItemsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestQuoteLineItemsPrompt',
  prompt: `You are an expert quote estimator for a services business. Your task is to analyze a job description, reference documents, past quotes, and available parts/labor to create a comprehensive list of line items for a new quote.

**Primary Job Information:**
User Prompt:
"{{{userPrompt}}}"

**Reference Documents:**
{{#each uploadedDocuments}}
- Document: {{{this.fileName}}}
  {{media url=this.dataUri}}
{{/each}}

**Context from Similar Past Quotes:**
{{#each previousQuotesContext}}
- Past Quote:
  \`\`\`json
  {{{this}}}
  \`\`\`
{{/each}}

**Available Parts & Labor Rates:**
- Parts Catalogue: \`\`\`json {{{json stringify=partsCatalogue}}} \`\`\`
- Labor Rates: \`\`\`json {{{json stringify=laborRates}}} \`\`\`

**Instructions:**
1.  **Analyze all inputs**: Carefully read the user prompt and analyze the content of any uploaded documents (text from RFQs, details from plans, etc.). Use the past quotes as a reference for how similar jobs were quoted.
2.  **Identify Parts**: From the Parts Catalogue, identify all necessary parts. Determine a reasonable quantity for each. Use the trade price from the catalogue as the \`unitCost\`. Calculate a reasonable \`unitPrice\` (sell price) based on the cost.
3.  **Estimate Labor**: From the available Labor Rates, determine the type and quantity (in hours) of labor required. Use the provided cost and standard rates for the \`unitCost\` and \`unitPrice\`.
4.  **Compile Line Items**: Create a single, comprehensive list of all suggested parts and labor line items.
5.  **Provide Reasoning**: Write a brief summary explaining your choices, noting any assumptions made.
6.  **Provide Disclaimer**: Include the following mandatory disclaimer: "These suggestions are generated by AI and are intended as a starting point. They may not be fully accurate or complete. Please review all line items, quantities, and prices carefully before sending to the client."

Format the entire output as a single JSON object that conforms to the output schema.
`,
});

const suggestQuoteLineItemsFlow = ai.defineFlow(
  {
    name: 'suggestQuoteLineItemsFlow',
  },
  async (input: SuggestQuoteLineItemsInput): Promise<SuggestQuoteLineItemsOutput> => {
    const { output } = await prompt(input);
    return output!;
  }
);
